# Generated by Django 4.1.1 on 2022-09-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
