# Generated by Django 4.1.1 on 2022-09-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_object_message_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='mdate',
        ),
    ]
