# Generated by Django 4.1.1 on 2022-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_message_mdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
